apiVersion: v1
kind: Namespace
metadata:
  name: architecturetest

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: publisher-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: publisher
  template:
    metadata:
      labels:
        app: publisher
    spec:
      containers:
      - name: publisher
        image: wastee941/softarchtest:publisher

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscriber-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscriber
  template:
    metadata:
      labels:
        app: subscriber
    spec:
      containers:
      - name: subscriber
        image: wastee941/softarchtest:subscriber
        ports:
        - containerPort: 80
        env:
        - name: DATABASE_URL
          value: postgresql://postgres:password@postgres:5432/mydatabase
        - name: DB_USER
          value: postgres
        - name: DB_HOST
          value: postgres-service
        - name: DB_NAME
          value: mydatabase
        - name: DB_PASSWORD
        - name: DB_PORT
          value: "5432"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: wastee941/softarchtest:api
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://+:80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
      - name: mosquitto
        image: eclipse-mosquitto:latest
        ports:
        - containerPort: 1883
          name: mqtt
        - containerPort: 9001
          name: mqtt-websockets
        volumeMounts:
        - name: config-volume
          mountPath: /mosquitto/config
      volumes:
      - name: config-volume
        configMap:
          name: mosquitto-config


---

apiVersion: v1
kind: Service
metadata:
  name: publisher-service
spec:
  selector:
    app: publisher
  ports:
  - name: mqtt
    port: 1883
    targetPort: 1883
  - name: mqtt-websockets
    port: 9001
    targetPort: 9001

---

apiVersion: v1
kind: Service
metadata:
  name: subscriber-service
spec:
  selector:
    app: subscriber
  ports:
  - name: http
    port: 80
    targetPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
  - name: http
    port: 80
    targetPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: mosquitto-service
spec:
  selector:
    app: mosquitto
  ports:
  - name: mqtt
    port: 1883
    targetPort: 1883
  - name: mqtt-websockets
    port: 9001
    targetPort: 9001

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432